AllCops:
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true

Metrics/ModuleLength:
  Max: 150
Metrics/MethodLength:
  Include: ["app/controllers/*"]
  Max: 20
Metrics/AbcSize:
  Include: ["app/controllers/*"]
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 10
Metrics/BlockLength:
  ExcludedMethods: ['describe']



Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle: key
Layout/LineLength:
  Max: 150
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
